class DefaultAddressMap:
    def __init__(self):
        self.province_map = {
            "alabama": "AL",
            "alaska": "AK",
            "arizona": "AZ",
            "arkansas": "AR",
            "california": "CA",
            "colorado": "CO",
            "connecticut": "CT",
            "delaware": "DE",
            "florida": "FL",
            "georgia": "GA",
            "hawaii": "HI",
            "idaho": "ID",
            "illinois": "IL",
            "indiana": "IN",
            "iowa": "IA",
            "kansas": "KS",
            "kentucky": "KY",
            "louisiana": "LA",
            "maine": "ME",
            "maryland": "MD",
            "massachusetts": "MA",
            "michigan": "MI",
            "minnesota": "MN",
            "mississippi": "MS",
            "missouri": "MO",
            "montana": "MT",
            "nebraska": "NE",
            "nevada": "NV",
            "new hampshire": "NH",
            "new jersey": "NJ",
            "new mexico": "NM",
            "new york": "NY",
            "north carolina": "NC",
            "north dakota": "ND",
            "ohio": "OH",
            "oklahoma": "OK",
            "oregon": "OR",
            "pennsylvania": "PA",
            "rhode island": "RI",
            "south carolina": "SC",
            "south dakota": "SD",
            "tennessee": "TN",
            "texas": "TX",
            "utah": "UT",
            "vermont": "VT",
            "virginia": "VA",
            "washington": "WA",
            "west virginia": "WV",
            "wisconsin": "WI",
            "wyoming": "WY",
            "district of columbia": "DC",
            "washington dc": "DC",
            "alberta": "AB",
            "british columbia": "BC",
            "manitoba": "MB",
            "new brunswick": "NB",
            "newfoundland and labrador": "NL",
            "nova scotia": "NS",
            "northwest territories": "NT",
            "nunavut": "NU",
            "ontario": "ON",
            "prince edward island": "PE",
            "quebec": "QC",
            "saskatchewan": "SK",
            "yukon": "YT",
            "al": "AL",
            "ak": "AK",
            "az": "AZ",
            "ar": "AR",
            "ca": "CA",
            "co": "CO",
            "ct": "CT",
            "de": "DE",
            "fl": "FL",
            "ga": "GA",
            "hi": "HI",
            "id": "ID",
            "il": "IL",
            "in": "IN",
            "ia": "IA",
            "ks": "KS",
            "ky": "KY",
            "la": "LA",
            "me": "ME",
            "md": "MD",
            "ma": "MA",
            "mi": "MI",
            "mn": "MN",
            "ms": "MS",
            "mo": "MO",
            "mt": "MT",
            "ne": "NE",
            "nv": "NV",
            "nh": "NH",
            "nj": "NJ",
            "nm": "NM",
            "ny": "NY",
            "nc": "NC",
            "nd": "ND",
            "oh": "OH",
            "ok": "OK",
            "or": "OR",
            "pa": "PA",
            "ri": "RI",
            "sc": "SC",
            "sd": "SD",
            "tn": "TN",
            "tx": "TX",
            "ut": "UT",
            "vt": "VT",
            "va": "VA",
            "wa": "WA",
            "wv": "WV",
            "wi": "WI",
            "wy": "WY",
            "dc": "DC",
            "ab": "AB",
            "bc": "BC",
            "mb": "MB",
            "nb": "NB",
            "nl": "NL",
            "ns": "NS",
            "nt": "NT",
            "nu": "NU",
            "on": "ON",
            "pe": "PE",
            "qc": "QC",
            "sk": "SK",
            "yt": "YT",
        }

        self.country_map = {
            'toronto': 'CA',
            'USA': 'US',
            'c.a.': 'CA',
            'canada': 'CA',
            'united states': 'US',
            'us': 'US',
            'united states of america': 'US',
            'u.s.': 'US',
            'ca': 'CA',
            'can': 'CA',
            'america': 'US',
            'can ': 'CA',
            'ca.': 'CA',
            'u.s.a.': 'US',
            'u s': 'US',
            'canada ': 'CA',
            'can123': 'CA',
            'c.a': 'CA',
            'usa': 'US',
            'u.s': 'US',
            'us of a': 'US',
            'ca-na-da': 'CA',
            'unitedstates': 'US',
            'u.s. of america': 'US',
            'can,': 'CA'
        }

    def check_map(self):
        if len(self.province_map) == 129 and len(self.country_map) == 25:
            print("-----------map is complete!-----------")
            return True
        else:
            raise Exception("Map is not complete. Please check the map.")

    def get_default_province_map(self):
        try:
            print("-----------checking map-----------")
            self.check_map()
            return self.province_map
        except Exception as e:
            print(f"Error: {e}")
            return None

    def get_default_country_map(self):
        try:
            print("-----------checking map-----------")
            self.check_map()
            return self.country_map
        except Exception as e:
            print(f"Error: {e}")
            return None
