province_super_map = {
	"ga 31909":  "GA",
	"pa":  "PA",
	"baltimore":  "MD",
	"west allis":  "WI",
	"ny 1 odell plaza":  "NY",
	"ny 12866":  "NY",
	"naperville":  "IL",
	"mn (5401 shoreline drive)":  "MN",
	"working at home - missouri":  "MO",
	"ky":  "KY",
	"us-ks":  "KS",
	"us-md":  "MD",
	"ga 31206":  "GA",
	"oh (15035 pearl rd)":  "OH",
	"nj 08505":  "NJ",
	"fl 32250":  "FL",
	"al - chelsea branch (birmingham":  "AL",
	"tx - 17 seventeen building branch":  "TX",
	"oconomowoc":  "WI",
	"az (remote)":  "AZ",
	"working at home - texas":  "TX",
	"working at home - alaska":  "AK",
	"nh":  "NH",
	"regina":  "SK",
	"ca usa":  "CA",
	"nj - 75 county road":  "NJ",
	"washington dc":  "DC",
	"sioux falls":  "SD",
	"indiana":  "IN",
	"tx":  "TX",
	"va 23606":  "VA",
	"fargo":  "ND",
	"me":  "ME",
	"ca 90660":  "CA",
	"durango colorado":  "CO",
	"12707 tamiami trl e - retail xfr1508":  "FL",
	"california - united states of america":  "CA",
	"mo (home & community based services)":  "MO",
	"ca - east manning ave":  "CA",
	"mo - corporate office":  "MO",
	"pa - 125 smithfield lane":  "PA",
	"nevada":  "NV",
	"tx (635 coit rd)":  "TX",
	"nj 08055":  "NJ",
	"working at home -massachusetts":  "MA",
	"us-il":  "IL",
	"working at home - california":  "CA",
	"la quinta":  "LA",
	"tn 37167":  "TN",
	"colorado evercommerce":  "CO",
	"in (201 & 203 northwestern ave.)":  "IN",
	"pa - 6145 delaware ave":  "PA",
	"illinois us":  "IL",
	"wy":  "WY",
	"nj - route 202":  "NJ",
	"oregon":  "OR",
	"ct - spring street":  "CT",
	"md 20774":  "MD",
	"ok - general area":  "OK",
	"de 19933":  "DE",
	"working at home -tennessee":  "TN",
	"nc":  "NC",
	"miami":  "FL",
	"mi - tittabawassee road":  "MI",
	"working at home - utah":  "UT",
	"fl (usa)":  "FL",
	"al - riverchase operations center (birmingham":  "AL",
	"md 21784":  "MD",
	"minnesota":  "MN",
	"working at home - virginia":  "VA",
	"hi":  "HI",
	"working at home - kansas":  "KS",
	"nj - edgeboro rd":  "NJ",
	"ks (williams foods)":  "KS",
	"working at home - colorado":  "CO",
	"fl 32405":  "FL",
	"us-tn":  "TN",
	"ne":  "NE",
	"us-ga":  "GA",
	"houston briarpark":  "TX",
	"us-nc":  "NC",
	"sc - remote":  "SC",
	"mi us":  "MI",
	"washington":  "WA",
	"ca - 4801 calloway dr":  "CA",
	"fl 34484":  "FL",
	"pa - 800 eaton ave":  "PA",
	"nc - concord mills boulevard":  "NC",
	"tx 78664":  "TX",
	"ns":  "NS",
	"fl 34135":  "FL",
	"connecticut":  "CT",
	"nv (8300 w cheyenne ave)":  "NV",
	"pa - 1021 park ave":  "PA",
	"nj 08310":  "NJ",
	"michigan":  "MI",
	"ga 31032":  "GA",
	"working at home - illinois":  "IL",
	"nv (remote)":  "NV",
	"working at home - pennsylvania":  "PA",
	"nj 07652":  "NJ",
	"los angeles":  "CA",
	"nj 08869":  "NJ",
	"nj 08225":  "NJ",
	"michigan - united states of america":  "MI",
	"mississauga":  "ON",
	"mi 48205":  "MI",
	"mn (usa)":  "MN",
	"lehi":  "UT",
	"ohio":  "OH",
	"danbury":  "CT",
	"nm 87144":  "NM",
	"nc - south sharon amity road":  "NC",
	"arkansas":  "AR",
	"nj (100 polar way":  "NJ",
	"longmont":  "CO",
	"ny 12208":  "NY",
	"wa 32125 32nd avenue south":  "WA",
	"nb":  "NB",
	"mo (outdoor world)":  "MO",
	"ga 31533":  "GA",
	"vergennes":  "VT",
	"fremont":  "CA",
	"ct":  "CT",
	"working at home - maine":  "ME",
	"orlando fl":  "FL",
	"fl retail":  "FL",
	"ga - regions plaza office":  "GA",
	"sd":  "SD",
	"pennsylvania":  "PA",
	"alabama":  "AL",
	"mo usa (8027 forsyth ste 900)":  "MO",
	"working at home - n carolina":  "NC",
	"working at home - kentucky":  "KY",
	"pa - 208 lifeline rd":  "PA",
	"maryland)":  "MD",
	"ut":  "UT",
	"working at home - delaware":  "DE",
	"ca (a valley blvd.)":  "CA",
	"georgia":  "GA",
	"nh 03079":  "NH",
	"ab - main banking centre":  "AB",
	"louisville":  "KY",
	"ms":  "MS",
	"in":  "IN",
	"ia":  "IA",
	"ab":  "AB",
	"us-ut":  "UT",
	"colorado":  "CO",
	"california":  "CA",
	"canada":  "ON",
	"pa - 100 st luke's lane":  "PA",
	"rockford":  "IL",
	"ga - 200 king mill":  "GA",
	"ks":  "KS",
	"il (lutheran hillside village)":  "IL",
	"pa - 250 s 21st street":  "PA",
	"nc (tdy)":  "NC",
	"il 60102":  "IL",
	"working at home - washington":  "WA",
	"il":  "IL",
	"elk grove":  "CA",
	"working at home-south dakota":  "SD",
	"dc":  "DC",
	"sunnyvale":  "CA",
	"delaware":  "DE",
	"or us":  "OR",
	"il 60487":  "IL",
	"nh (tdy)":  "NH",
	"new york":  "NY",
	"al (arsenal)":  "AL",
	"tn - nashville operations center":  "TN",
	"tucson":  "AZ",
	"pa - 500 st. luke's drive":  "PA",
	"missouri":  "MO",
	"ar - martin luther king jr blvd":  "AR",
	"wa (robert thompson road)":  "WA",
	"ca 91731":  "CA",
	"us-wi":  "WI",
	"tx (tracker boating center)":  "TX",
	"oh (montgomery)":  "OH",
	"tn 38305":  "TN",
	"pa 19380":  "PA",
	"working at home - florida":  "FL",
	"nj 07702":  "NJ",
	"fl 32703":  "FL",
	"working at home - louisiana":  "LA",
	"tx us":  "TX",
	"plano":  "TX",
	"us-pa":  "PA",
	"pa - 153 brodhead rd":  "PA",
	"fl 33870":  "FL",
	"al":  "AL",
	"nv":  "NV",
	"fresno":  "CA",
	"ca (15270 antioch st # 15276)":  "CA",
	"wi":  "WI",
	"kansas":  "KS",
	"tx (pioneer frozen foods)":  "TX",
	"mn (726 main street)":  "MN",
	"pa 19425":  "PA",
	"nc (headquarters)":  "NC",
	"tx (the morrison milling company)":  "TX",
	"working at home -  arkansas":  "AR",
	"ga - lyons distribution center":  "GA",
	"ca":  "CA",
	"on":  "ON",
	"ar terminal office - springdale":  "AR",
	"south dakota":  "SD",
	"bismarck":  "ND",
	"pa - 1941 hamilton st":  "PA",
	"ca 90255":  "CA",
	"pa - 1736 hamilton st":  "PA",
	"233 s wacker dr":  "IL",
	"massachusetts":  "MA",
	"mn (9 third avenue nw suite 135)":  "MN",
	"md 21638":  "MD",
	"odessa tx 79762-5939":  "TX",
	"sc 29579":  "SC",
	"virginia":  "VA",
	"wi - wgba/wacy":  "WI",
	"mn (10400 baltimore street suite b-124)":  "MN",
	"ca 90040":  "CA",
	"working at home - arizona":  "AZ",
	"fl 34668":  "FL",
	"fl - hallandale boulevard":  "FL",
	"sd (902 mount rushmore)":  "SD",
	"mi 48101":  "MI",
	"wa":  "WA",
	"working at home - conneticut":  "CT",
	"working at home - north dakota":  "ND",
	"md (595 gov ritchie highway)":  "MD",
	"us-oh":  "OH",
	"utah":  "UT",
	"st paul":  "MN",
	"working at home - michigan":  "MI",
	"wa (remote)":  "WA",
	"md 20852":  "MD",
	"california 92408":  "CA",
	"pa - 1441 schoenersville rd":  "PA",
	"wi - national office":  "WI",
	"ny - leprechaun lane":  "NY",
	"albany":  "NY",
	"mountain view":  "CA",
	"ny - east circle drive":  "NY",
	"nv (4626 s maryland pkwy)":  "NV",
	"fl (nw 113th court)":  "FL",
	"eden prairie":  "MN",
	"working at home - new hampshire":  "NH",
	"ks usa":  "KS",
	"co":  "CO",
	"santa ana":  "CA",
	"ma mercantile center":  "MA",
	"ny retail":  "NY",
	"british columbia":  "BC",
	"iowa":  "IA",
	"working at home - montana":  "MT",
	"kentucky":  "KY",
	"va 23150":  "VA",
	"fl - downtown tampa building":  "FL",
	"ma - alltown":  "MA",
	"vt":  "VT",
	"bc":  "BC",
	"al - riverchase north building (birmingham":  "AL",
	"working at home - hawaii":  "HI",
	"co retail":  "CO",
	"mn (4606 nicollet avenue s)":  "MN",
	"pa 19043":  "PA",
	"mo (mason pointe)":  "MO",
	"w. des moines":  "IA",
	"tn - north riverside drive":  "TN",
	"bc - richmond banking centre":  "BC",
	"ny - 92nd street":  "NY",
	"pa 19050":  "PA",
	"working at home - maryland":  "MD",
	"working at home - idaho":  "ID",
	"tn - hwy 70 s":  "TN",
	"ga 30290":  "GA",
	"working at home - new mexico":  "NM",
	"mb":  "MB",
	"or (remote)":  "OR",
	"pa 19020":  "PA",
	"ks - college/mn br":  "KS",
	"louisiana us":  "LA",
	"us-tx":  "TX",
	"de - 26581 lewes georgetown hwy":  "DE",
	"nd":  "ND",
	"nj 08005":  "NJ",
	"hawaii":  "HI",
	"ny (260 state street":  "NY",
	"md (tdy)":  "MD",
	"fl 32751":  "FL",
	"ny (1271 aoa/6th ave)":  "NY",
	"ok":  "OK",
	"mo 64068":  "MO",
	"nc - ninth street":  "NC",
	"ca (1552 fitzgerald dr)":  "CA",
	"ny":  "NY",
	"ca 90280":  "CA",
	"il - remote":  "IL",
	"ca (tdy)":  "CA",
	"pa 18018":  "PA",
	"working at home - alabama":  "AL",
	"ca (remote)":  "CA",
	"ne - kmtv":  "NE",
	"nc - berkeley blvd":  "NC",
	"ca 92805":  "CA",
	"ma - corporate headquarters":  "MA",
	"mi 48084":  "MI",
	"pa - 406 delaware ave":  "PA",
	"co 80108":  "CO",
	"ga 30662":  "GA",
	"nv (3837 blue diamond rd)":  "NV",
	"ga":  "GA",
	"ca 444 spear street":  "CA",
	"virginia us":  "VA",
	"san jose":  "CA",
	"mn (tmw)":  "MN",
	"ga 30533":  "GA",
	"minneapolis mn 55403-2542":  "MN",
	"working at home - oklahoma":  "OK",
	"pa 19038":  "PA",
	"bc - vancouver main banking centre":  "BC",
	"oklahoma":  "OK",
	"ma memorial campus":  "MA",
	"wv":  "WV",
	"nova scotia":  "NS",
	"working at home - mississippi":  "MS",
	"nc - for recruiting only":  "NC",
	"ottawa":  "ON",
	"la":  "LA",
	"tn - west nashville branch":  "TN",
	"mn (1147 - 2nd street sw)":  "MN",
	"ca bldg 676 1801 west hughes drive building 676":  "CA",
	"mn (17830 kenwood trail)":  "MN",
	"pa - 120 pine st":  "PA",
	"co 80238":  "CO",
	"tennessee":  "TN",
	"il (concordia village)":  "IL",
	"mo usa (8027 forsyth ste 800)":  "MO",
	"nj - main campus":  "NJ",
	"mississippi":  "MS",
	"nj 08753":  "NJ",
	"nj":  "NJ",
	"ny 20 loudonville road":  "NY",
	"working at home - new jersey":  "NJ",
	"texas":  "TX",
	"tinley park":  "IL",
	"ga 31210":  "GA",
	"nc - operations":  "NC",
	"new mexico":  "NM",
	"working at home - minnesota":  "MN",
	"fl - ft lauderdale office":  "FL",
	"pa - 211 n. 12th st":  "PA",
	"mn (2051 washington ave)":  "MN",
	"st louis children's hospital":  "MO",
	"az 85251":  "AZ",
	"wi 54915":  "WI",
	"pa 18940":  "PA",
	"mn (4680 s roberts trail)":  "MN",
	"glen allen":  "VA",
	"ny (230 park ave)":  "NY",
	"ny 12203":  "NY",
	"tn":  "TN",
	"us-ok":  "OK",
	"444 n michigan ave":  "IL",
	"mo (lenoir woods)":  "MO",
	"asheville":  "NC",
	"nc - jw clay boulevard":  "NC",
	"in - east 96th street":  "IN",
	"ca 90027":  "CA",
	"mi 48168":  "MI",
	"ny (gdc) 1181":  "NY",
	"ar - clarksville main branch":  "AR",
	"ca 90640":  "CA",
	"sc 29621":  "SC",
	"norwalk":  "CT",
	"ga 30529":  "GA",
	"mi 48059":  "MI",
	"nj 08106":  "NJ",
	"ab - cwb credit support centre":  "AB",
	"mn (1560 coon rapids blvd)":  "MN",
	"pa - sycamore str":  "PA",
	"port wentworth ga 31407-9257":  "GA",
	"texas us":  "TX",
	"working at home - iowa":  "IA",
	"working at home - rhode island":  "RI",
	"fl 33446":  "FL",
	"wi - gale st":  "WI",
	"ny 12205":  "NY",
	"michigan us":  "MI",
	"south carolina":  "SC",
	"ga 31701":  "GA",
	"ar":  "AR",
	"ny one penn plaza":  "NY",
	"fl - wftx":  "FL",
	"working at home - nebraska":  "NE",
	"al - regions center":  "AL",
	"ca (17833 hesperian blvd.)":  "CA",
	"ca - tyler st":  "CA",
	"tampa":  "FL",
	"nj 08330":  "NJ",
	"az - frye road":  "AZ",
	"va":  "VA",
	"nc - east independence boulevard":  "NC",
	"al - eastwood branch":  "AL",
	"ga 30909":  "GA",
	"nm":  "NM",
	"tx (ho)":  "TX",
	"saskatchewan":  "SK",
	"nj 08053":  "NJ",
	"washington st.":  "WA",
	"oh":  "OH",
	"pa 19149":  "PA",
	"nj 08857":  "NJ",
	"de 200 powder mill road":  "DE",
	"mt":  "MT",
	"manitoba":  "MB",
	"indianapolis":  "IN",
	"texas (research blvd)":  "TX",
	"working at home - oregon":  "OR",
	"sc":  "SC",
	"ct 212 west newberry rd":  "CT",
	"de":  "DE",
	"tx 75062 vizient corporate hq":  "TX",
	"spokane":  "WA",
	"fl 33805":  "FL",
	"ca - remote":  "CA",
	"ca 90057":  "CA",
	"sk":  "SK",
	"mo":  "MO",
	"ny (usa)":  "NY",
	"pa - 100 st. lukes lane":  "PA",
	"ga 31024":  "GA",
	"ab - cwb wealth":  "AB",
	"nj 08026":  "NJ",
	"de 19703":  "DE",
	"pa usa":  "PA",
	"nj 08872":  "NJ",
	"fl - cityplace regional office (palm beach":  "FL",
	"west virginia":  "WV",
	"mn 55044":  "MN",
	"kitchener":  "ON",
	"or 97060":  "OR",
	"pa - 5425 lanark road":  "PA",
	"wisconsin":  "WI",
	"district of columbia":  "DC",
	"ny 12084":  "NY",
	"fl - university boulevard branch (orlando":  "FL",
	"littleton co 80123-2202":  "CO",
	"pa - easton road":  "PA",
	"fort worth":  "TX",
	"in - southport road":  "IN",
	"tx manufacturing facility":  "TX",
	"ny 14586":  "NY",
	"quebec":  "QC",
	"ma bldg 3 concord 50 apple hill drive concord - building 3":  "MA",
	"tx (pearl st)":  "TX",
	"wi (544 e ogden ave)":  "WI",
	"id":  "ID",
	"ga 30265":  "GA",
	"tx - tyler main branch":  "TX",
	"ancaster":  "ON",
	"fl - orange city branch (port orange":  "FL",
	"oh 45014":  "OH",
	"lone tree co 80124-5547":  "CO",
	"ia - prairie val":  "IA",
	"usa-mn":  "MN",
	"ca - ksby":  "CA",
	"nj 08009":  "NJ",
	"ca - 5650 southern":  "CA",
	"co 9750 e. easter avenue":  "CO",
	"working at home-south carolina":  "SC",
	"petaluma":  "CA",
	"idaho":  "ID",
	"az":  "AZ",
	"pa - 801 ostrum st":  "PA",
	"nj 07731":  "NJ",
	"maryland":  "MD",
	"2901 sw 149th ave":  "FL",
	"ca 90303":  "CA",
	"mn":  "MN",
	"working at home - indiana":  "IN",
	"ma us":  "MA",
	"va (chemical way)":  "VA",
	"alberta":  "AB",
	"co (usa)":  "CO",
	"nv (7541 w lake mead blvd ste 1)":  "NV",
	"nv 89015":  "NV",
	"ma 1001 boston post road building 2":  "MA",
	"ri":  "RI",
	"mn (520 jefferson blvd)":  "MN",
	"sd usa":  "SD",
	"fl":  "FL",
	"san luis obispo":  "CA",
	"mo - branch":  "MO",
	"new york (harris-ips)":  "NY",
	"louisiana":  "LA",
	"pe":  "PE",
	"or - suttle rd.":  "OR",
	"working at home - nevada":  "NV",
	"wi (usa)":  "WI",
	"8554 huebner rd":  "TX",
	"mb - cwb national leasing corporate office":  "MB",
	"ga 30643":  "GA",
	"mckinney 2501 west university":  "TX",
	"in - wrtv":  "IN",
	"mi":  "MI",
	"mesa":  "AZ",
	"mo (laclede groves)":  "MO",
	"illinois":  "IL",
	"san diego":  "CA",
	"working at home - ohio":  "OH",
	"tx (remote)":  "TX",
	"el paso":  "TX",
	"ab - 102nd nw ave (081)":  "AB",
	"cambridge":  "ON",
	"az 85286":  "AZ",
	"ia (usa)":  "IA",
	"ne gateway drive":  "NE",
	"mi 48336":  "MI",
	"mi 4905 stariha drive":  "MI",
	"new jersey":  "NJ",
	"tn - nashboro village branch":  "TN",
	"ma":  "MA",
	"mi 48214":  "MI",
	"ny - suny - tcm - wolfspeed":  "NY",
	"il (meridian village)":  "IL",
	"mn (307 north nokomis square suite 113)":  "MN",
	"md":  "MD",
	"ontario":  "ON",
	"nc retail":  "NC",
	"topeka":  "KS",
	"tx - w. university drive (us 380)":  "TX",
	"mo (breeze park)":  "MO",
	"vt (usa)":  "VT",
	"working at home - vermont":  "VT",
	"il 60707":  "IL",
	"ca 92647":  "CA",
	"mo (usa)":  "MO",
	"working at home - wisconsin":  "WI",
	"ky - franklin branch":  "KY",
	"ridgefield park":  "NJ",
	"dallas":  "TX",
	"arizona)":  "AZ",
	"tn - bordeaux branch":  "TN",
	"florida":  "FL",
	"north carolina (home office)":  "NC",
	"fl (remote)":  "FL",
	"pa retail":  "PA",
	"va - atlantic ave":  "VA",
	"bc - 198 st (042)":  "BC",
	"nj 08723":  "NJ",
	"pa (usa)":  "PA",
	"mn (ummc - east bank)":  "MN",
	"11200 rockville pike":  "MD",
	"co - 5100 e ave":  "CO",
	"working at home - wyoming":  "WY",
	"roseville":  "CA",
	"nebraska":  "NE",
	"qc":  "QC",
	"denver":  "CO",
	"ma university campus":  "MA",
	"east hartford":  "CT",
	"murfreesboro":  "TN",
	"nc - highway 64 & village park dr.":  "NC",
	"north carolina":  "NC",
	"de 19707":  "DE",
	"arizona":  "AZ",
	"ab - cwb corporate office":  "AB",
	"or":  "OR",
	"10600 tamiami trail - retail xfr1507":  "FL",
	"ma headquarters - (nb)":  "MA",
	"fl (1216 north monroe street)":  "FL",
	"sc - pelham road":  "SC",
	"pa 18045":  "PA",
	"ne (retail)":  "NE",
	"working at home - georgia":  "GA",
	"nc - charlotte uptown branch":  "NC",
	"working at home - w virginia":  "VA",
	"oh us":  "OH",
	"pa 18301":  "PA",
}
